version: "3.8"

services:
  app-repo:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-repo
    entrypoint: sh ./.docker/entrypoint.sh
    ports:
      - 3010:3010
    volumes:
      - ./:/usr/app-repo/app
    networks:
      - app-repo
    environment:
      APP_VERSION: 1.0
      APP_NAME: "Template Repo"
      APP_PORT: 3010

networks:
  app-repo:
    driver: bridge